### ISSUE TITLE
More complexe exemple

### ISSUE THREAD

**Issue by Grummfy** [tablexi/chef-nginx_conf#15]
Hello,
it should be intresting to add more complexe exemple in the doc parts.

By exemple

´´´
nginx_conf_file "mywebsite.com" do
  socket "/var/www/myapp/shared/tmp/sockets/unicorn.socket"
	options['autoindex'] = 'on'
	options['index'] = 'index.html index.htm'
end
´´´

**Comment by phoolish** [comment]
PR's always accepted.  Closing due to age.
