### ISSUE TITLE
blocks in locations attributes are followed with ';'

### ISSUE THREAD

**Issue by Yueyehua** [tablexi/chef-nginx_conf#27]
Hi,
I'm trying to put an if statement in location directive using your cookbook but when I write :

'locations' => {
  '/' => {
    'block' =>
          "if ($http_user_agent ~ docker) {proxy_pass http://registry;}" 
  }
}

It generates a ';' after the '}'.

Thanks for your time and regards,

**Comment by phoolish** [comment]
it is better to write it like this:
``` ruby
'locations' => {
  '/' => {
    'if' => {
      "$http_user_agent ~ docker" => "proxy_pass http://registry"
    }
}
```

**Comment by Yueyehua** [comment]
Hi,
Yes, it worked (with an array of directive).
Thanks, =)
